"use client";
import Link from 'next/link';
import {ArrowDown,ArrowUpRight,FileSpreadsheet,LockKeyhole,MoveRight,Package,ScanLine,ShieldCheck} from 'lucide-react';
import {PublicShell} from './public-shell';
import {useLanguage,useSiteSettings} from './providers';
import {displayRupees,type PublicPricing} from './use-pricing';
import {publicFaqs,publicFaqsHinglish} from '@/core/content';
import {WebsiteJourney} from './website-journey';
import {MarketplaceBrandRow} from './marketplace-brand-row';

export function WebsiteLanding({pricing}:{pricing:PublicPricing}){
 const {language}=useLanguage();const {settings}=useSiteSettings();const en=language==='english';
 const capabilities=[{icon:ScanLine,n:'01',title:en?'See the margin.':'मार्जिन समझें।',text:en?'Trace contribution to your settlements and product costs.':'सेटलमेंट और उत्पाद लागत से अपनी कमाई समझें।',href:'/analyze'}, {icon:Package,n:'02',title:en?'Find the friction.':'नुकसान की वजह जानें।',text:en?'Spot return exposure, loss-making SKUs and missing costs.':'रिटर्न का जोखिम, नुकसान वाले SKU और बाकी लागत देखें।',href:'/guides'}, {icon:FileSpreadsheet,n:'03',title:en?'Make your next move.':'अगला कदम तय करें।',text:en?'Start with the issues that have evidence behind them.':'उन मुद्दों से शुरू करें जिनका हिसाब उपलब्ध है।',href:'/methodology'}];
 return <PublicShell><main className="website-home" lang={en?'en':'hi'}>
  <section className="website-hero website-container"><div className="hero-copy"><p className="website-eyebrow"><span/>{en?'A CLEARER VIEW OF YOUR BUSINESS':'आपके कारोबार का साफ़ हिसाब'}</p><h1>{en?settings.hero.headlineEnglish:settings.hero.headlineHinglish}</h1><p className="hero-description">{en?'Your reports. Your costs. A clear view of what you earn—and what needs attention.':'आपकी रिपोर्ट। आपकी लागत। कमाई और ध्यान देने वाली बातों का साफ़ हिसाब।'}</p><div className="hero-actions"><Link className="website-button" href="/analyze">{en?'Check my profit':'मेरा लाभ देखें'}<ArrowUpRight size={19}/></Link><a className="website-text-link" href="#money-journey">{en?'See how it works':'देखें कैसे काम करता है'}<ArrowDown size={16}/></a></div><p className="hero-footnote"><LockKeyhole size={13}/>{en?'Free first check. Your report stays on your device.':'पहली जाँच मुफ़्त। रिपोर्ट आपके डिवाइस पर रहती है।'}</p></div><div className="hero-marketplaces"><div className="hero-marketplace-card"><p className="hero-marketplace-kicker">{en?'BUILT AROUND THE WAY YOU SELL.':'आप जहाँ बेचते हैं, उसी हिसाब से।'}</p><MarketplaceBrandRow/><Link className="hero-marketplace-link" href="/marketplaces">{en?'Explore supported workflows':'समर्थित तरीके देखें'}<ArrowUpRight size={15}/></Link></div><span className="marketplace-orb marketplace-orb-one" aria-hidden="true"/><span className="marketplace-orb marketplace-orb-two" aria-hidden="true"/><span className="marketplace-orb marketplace-orb-three" aria-hidden="true"/></div></section>
  <WebsiteJourney english={en}/>
  <section className="website-capabilities website-container"><div className="website-section-heading"><p className="website-eyebrow">{en?'LESS GUESSWORK. MORE CONTROL.':'अनुमान कम। समझ ज़्यादा।'}</p><h2>{en?'Good decisions start\nwith a clear picture.':'अच्छे निर्णय की शुरुआत\nसाफ़ हिसाब से होती है।'}</h2><Link className="website-text-link" href="/calculators">{en?'Explore free calculators':'मुफ़्त कैलकुलेटर देखें'}<ArrowUpRight size={17}/></Link></div><div className="capability-grid">{capabilities.map(({icon:Icon,n,title,text,href})=><Link className="website-capability" key={n} href={href}><div className="capability-top"><Icon size={23} strokeWidth={1.6}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p><ArrowUpRight className="capability-arrow" size={21}/></Link>)}</div></section>
  <section className="website-trust website-container"><div className="trust-copy"><p className="website-eyebrow">{en?'CLARITY INCLUDES THE UNKNOWNS':'अधूरे हिसाब की भी पहचान'}</p><h2>{en?'Confidence,\nwith a reason.':'भरोसा,\nपूरे हिसाब के साथ।'}</h2><p>{en?'A settlement is not a bank credit. A sale is not profit. SellerHisab keeps the distinctions visible.':'सेटलमेंट बैंक में आया पैसा नहीं है। बिक्री लाभ नहीं है। SellerHisab इनका अंतर साफ़ रखता है।'}</p><Link href="/methodology" className="website-text-link">{en?'Our methodology':'हमारी गणना का तरीका'}<ArrowUpRight size={17}/></Link></div><div className="confidence-board">{[{label:en?'Confirmed':'पुष्ट',status:'confirmed',text:en?'Required evidence is available.':'ज़रूरी जानकारी उपलब्ध है।'},{label:en?'Provisional':'संभावित',status:'provisional',text:en?'Pending adjustments can change the result.':'बाकी समायोजन से परिणाम बदल सकता है।'},{label:en?'Incomplete':'अधूरा',status:'incomplete',text:en?'Missing inputs are shown, never guessed.':'बाकी जानकारी दिखाई जाती है, अनुमान नहीं।'}].map(item=><div className="confidence-row" key={item.status}><span className={`confidence-dot ${item.status}`}/><strong>{item.label}</strong><p>{item.text}</p></div>)}<div className="trust-privacy"><ShieldCheck size={22}/><span>{en?'Raw report files are processed on your device.':'रिपोर्ट की गणना आपके डिवाइस पर होती है।'}<Link href="/privacy">{en?'Read privacy policy':'गोपनीयता नीति पढ़ें'}</Link></span></div></div></section>
  <section className="website-pricing-teaser website-container"><div><p className="website-eyebrow">{en?'START WITH CLARITY':'साफ़ हिसाब से शुरुआत'}</p><h2>{en?'Your first insight\ncosts nothing.':'पहली समझ।\nबिना किसी शुल्क के।'}</h2><p>{en?'Run a free check. Choose more depth when you need it.':'मुफ़्त जाँच करें। ज़रूरत पर अधिक जानकारी वाला प्लान चुनें।'}</p><Link className="website-text-link" href="/pricing">{en?'Compare all plans':'सभी प्लान की तुलना करें'}<ArrowUpRight size={17}/></Link></div><div className="teaser-plans">{[
   {name:en?'Free Check':'मुफ़्त जाँच',price:'₹0',suffix:'',href:'/analyze',cta:en?'Start free':'मुफ़्त शुरू करें',tone:'free'},
   {name:'Action Report',price:displayRupees(pricing.actionReportPaise),suffix:en?'one-time':'एक बार',href:'/analyze',cta:en?'Analyze first':'पहले analysis करें',tone:'action'},
   {name:'Starter',price:displayRupees(pricing.starterMonthlyPaise),suffix:`/${en?'month':'माह'}`,href:'/app/billing?plan=starter',cta:en?'Choose Starter':'Starter चुनें',tone:'starter'},
   {name:'Pro',price:displayRupees(pricing.proMonthlyPaise),suffix:`/${en?'month':'माह'}`,href:'/app/billing?plan=pro',cta:en?'Choose Pro':'Pro चुनें',tone:'pro'},
  ].map(plan=><div key={plan.name} className={`teaser-plan teaser-plan-${plan.tone}`}><span>{plan.name}</span><strong>{plan.price}{plan.suffix&&<small>{plan.suffix}</small>}</strong><Link href={plan.href}>{plan.cta}<MoveRight size={17}/></Link></div>)}</div></section>
  <section className="website-faq website-container"><div><p className="website-eyebrow">{en?'BEFORE YOU START':'शुरू करने से पहले'}</p><h2>{en?'A few good questions.':'कुछ ज़रूरी सवाल।'}</h2></div><div className="website-faq-list">{(en?publicFaqs:publicFaqsHinglish).map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="website-final-cta website-container"><span className="website-eyebrow">{en?'YOUR BUSINESS. IN FOCUS.':'आपका कारोबार। साफ़ नज़र।'}</span><h2>{en?'Make the numbers\nwork for you.':'हिसाब समझें।\nआगे बढ़ें।'}</h2><Link className="website-button" href="/analyze">{en?'Check my profit — free':'मेरा लाभ देखें — मुफ़्त'}<ArrowUpRight size={19}/></Link></section>
 </main></PublicShell>;
}
