import { pbkdf2 } from "node:crypto";
import { constantTimeEqual } from "./crypto";

const encoder = new TextEncoder();

/**
 * Cloudflare Workers production currently rejects PBKDF2 calls above 100,000
 * iterations even when the request originates through node:crypto. Keep every
 * runtime PBKDF2 invocation at or below that ceiling.
 *
 * v3 is the production-safe format. Historical unversioned 100k hashes remain
 * verifiable and are upgraded after a successful login. The short-lived v2
 * 600k format produced by the F15 hardening build cannot be verified in the
 * production Workers runtime, so affected users must perform a one-time OTP
 * password reset rather than receiving a 500/503 from the KDF.
 */
export const PASSWORD_VERSION = "v3";
export const PASSWORD_ITERATIONS = 100_000;
export const WORKERS_PBKDF2_MAX_ITERATIONS = 100_000;
const LEGACY_ITERATIONS = 100_000;
const RETIRED_V2_ITERATIONS = 600_000;
const KEY_BYTES = 32;

type ParsedPasswordHash = {
  version: "v2" | "v3" | null;
  scheme: string;
  iterations: number;
  saltValue: string;
  hashValue: string;
};

export function validatePassword(password: string): string {
  if (password.length < 8) throw new Error("Password must be at least 8 characters.");
  if (password.length > 128) throw new Error("Password is too long.");
  return password;
}

export function validateAdminPassword(password: string): string {
  if (password.length < 12) throw new Error("Admin password must be at least 12 characters.");
  if (password.length > 128) throw new Error("Admin password is too long.");
  if (!/[a-z]/.test(password)) throw new Error("Admin password must include a lowercase letter.");
  if (!/[A-Z]/.test(password)) throw new Error("Admin password must include an uppercase letter.");
  if (!/\d/.test(password)) throw new Error("Admin password must include a number.");
  if (!/[^A-Za-z0-9]/.test(password)) throw new Error("Admin password must include a symbol.");
  return password;
}

export async function hashPassword(password: string): Promise<string> {
  validatePassword(password);
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const hash = await derive(password, salt, PASSWORD_ITERATIONS);
  return `${PASSWORD_VERSION}$pbkdf2_sha256$${PASSWORD_ITERATIONS}$${toBase64url(salt)}$${toBase64url(hash)}`;
}

export async function verifyPassword(password: string, encoded: string | null | undefined): Promise<boolean> {
  if (!encoded || password.length > 128 || !password.length) return false;
  const parsed = parsePasswordHash(encoded);
  if (!parsed) return false;

  const supportedCurrent = parsed.version === PASSWORD_VERSION && parsed.iterations === PASSWORD_ITERATIONS;
  const supportedLegacy = parsed.version === null && parsed.iterations === LEGACY_ITERATIONS;
  if (!supportedCurrent && !supportedLegacy) return false;

  let salt: Uint8Array;
  let expected: Uint8Array;
  try {
    salt = fromBase64url(parsed.saltValue);
    expected = fromBase64url(parsed.hashValue);
  } catch {
    return false;
  }
  if (salt.byteLength !== 16 || expected.byteLength !== KEY_BYTES) return false;

  const actual = await derive(password, salt, parsed.iterations);
  return constantTimeEqual(toBase64url(actual), toBase64url(expected));
}

/**
 * v2/600k credentials were generated by the F15 hardening build but cannot be
 * evaluated by the production Workers PBKDF2 implementation. They are never
 * silently weakened or guessed: a verified OTP reset creates a v3 credential.
 */
export function passwordResetRequired(encoded: string | null | undefined): boolean {
  const parsed = encoded ? parsePasswordHash(encoded) : null;
  return Boolean(parsed && parsed.version === "v2" && parsed.iterations === RETIRED_V2_ITERATIONS);
}

export function passwordNeedsRehash(encoded: string | null | undefined): boolean {
  if (!encoded || passwordResetRequired(encoded)) return false;
  const parsed = parsePasswordHash(encoded);
  if (!parsed) return false;
  return parsed.version === null && parsed.iterations === LEGACY_ITERATIONS;
}

export function validatePasswordForIdentity(password: string, admin: boolean): string {
  return admin ? validateAdminPassword(password) : validatePassword(password);
}

export function publicPasswordValidationMessage(error: unknown): string | null {
  const message = error instanceof Error ? error.message : "";
  return /^(Password must|Password is too long\.|Admin password must)/.test(message) ? message : null;
}

function parsePasswordHash(encoded: string): ParsedPasswordHash | null {
  let version: ParsedPasswordHash["version"] = null;
  let body = encoded;
  if (encoded.startsWith("v3$")) {
    version = "v3";
    body = encoded.slice(3);
  } else if (encoded.startsWith("v2$")) {
    version = "v2";
    body = encoded.slice(3);
  } else if (/^v\d+\$/.test(encoded)) {
    return null;
  }

  const [scheme, rounds, saltValue, hashValue, extra] = body.split("$");
  if (scheme !== "pbkdf2_sha256" || extra || !rounds || !saltValue || !hashValue) return null;
  const iterations = Number(rounds);
  if (!Number.isInteger(iterations) || iterations < 1 || iterations > RETIRED_V2_ITERATIONS) return null;
  if (!/^[A-Za-z0-9_-]{22}$/.test(saltValue) || !/^[A-Za-z0-9_-]{43}$/.test(hashValue)) return null;
  return { version, scheme, iterations, saltValue, hashValue };
}

async function derive(password: string, salt: Uint8Array, iterations: number): Promise<Uint8Array> {
  if (iterations > WORKERS_PBKDF2_MAX_ITERATIONS) {
    throw new Error("Password KDF parameters exceed the production runtime limit.");
  }
  return new Promise((resolve, reject) => {
    pbkdf2(encoder.encode(password), salt, iterations, KEY_BYTES, "sha256", (error, key) => {
      if (error) reject(error); else resolve(new Uint8Array(key));
    });
  });
}

function toBase64url(bytes: Uint8Array): string {
  let binary = "";
  bytes.forEach((byte) => { binary += String.fromCharCode(byte); });
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

function fromBase64url(value: string): Uint8Array {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  return Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
}
