import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";
export const metadata: Metadata = { title: "Terms of Use", description: "Terms for using SellerHisab analytical tools and reports.", alternates: { canonical: "/terms" } };
export default function TermsPage() { return <InfoPage eyebrow="Terms of use" title="Clear limits for financial decision support" intro="By using SellerHisab, you agree to use it as an analytical utility based on files and assumptions you supply." sections={[
  { title: "Permitted use", bullets: ["Use your own or lawfully authorized seller reports.", "Do not upload malicious archives, attempt abuse, reverse payment checks or disrupt the service.", "Do not use the product to file taxes, claims or legal submissions without independent verification."] },
  { title: "Analytical estimates", paragraphs: ["Contribution and recommended actions depend on report format, period coverage, status evidence and seller-entered costs. The product does not guarantee profit recovery, marketplace payment, business outcome or report completeness."] },
  { title: "Your responsibility", paragraphs: ["You are responsible for verifying product costs, packaging, ads, taxes, overhead and marketplace records before acting. Strong actions such as pausing or scaling should also consider inventory, customer demand and operational context outside supplied files."] },
  { title: "Accounts, free trials and payments", paragraphs: ["Keep account access secure. Paid entitlements may be suspended or revoked after refund, chargeback, fraud or material abuse. Subscription access follows the provider-confirmed billing state.", "When a Starter or Pro free trial is enabled, activation requires Razorpay AutoPay/mandate authorisation. The recurring plan charge begins after the displayed trial period unless the subscription is cancelled first. One free trial is available per SellerHisab account across recurring plans. Razorpay may perform its own authentication step under its payment terms."] },
  { title: "Availability and parser changes", paragraphs: ["Marketplace report formats can change. Unknown critical layouts fail closed. Parser support and compatibility may be updated to preserve correctness; availability is not guaranteed for every historical or future format."] },
  { title: "Independent status", paragraphs: ["SellerHisab is independent and is not affiliated with, endorsed by or an official product of any marketplace or commerce platform. Marketplace names are used descriptively to identify report compatibility."] },
]} note="These terms are a practical launch policy and should be reviewed by qualified Indian counsel before a large public commercial launch." />; }
