import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Calculation Methodology", description: "SellerHisab Sales, Settlement, Bank Cash, Return/RTO, ads, costs aur profit ko kaise calculate karta hai — simple language me.", alternates: { canonical: "/methodology" } };

export default function MethodologyPage() { return <InfoPage eyebrow="Simple rules, clear hisaab" title="Calculation Methodology" intro="SellerHisab ka basic rule simple hai: jo report aur cost aap dete ho, calculation usi par hoti hai. Koi important data missing ho to system guess karke fake profit nahi dikhata." sections={[
  { title: "Sales, Settlement, Bank Cash aur Profit", paragraphs: ["Sales = order ki value. Settlement = marketplace ka payout. Bank Cash = bank me actual aaya paisa. Profit dekhte waqt product cost, packaging, ads aur jo doosre costs available hain unko count kiya jata hai. Required costs complete na hon to Full Net Profit confirm nahi kiya jata."] },
  { title: "Confirmed, Provisional aur Incomplete ka matlab", bullets: ["Confirmed: zaroori cost, settlement aur order/return status clear hai, isliye number par zyada bharosa kiya ja sakta hai.", "Provisional: abhi calculation ho sakti hai, lekin pending settlement, return, exchange ya adjustment se number badal sakta hai.", "Incomplete: koi important cost ya data missing hai. Aise result ko SellerHisab zabardasti confirmed profit me add nahi karta."] },
  { title: "Product cost aur packaging", paragraphs: ["Delivered item par product cost count hoti hai. Shipped order par packaging cost count ho sakti hai. Return/RTO me damage ya recovery ka clear proof report me na ho to SellerHisab apni taraf se koi fake damage amount assume nahi karta."] },
  { title: "Return / RTO se kitna loss ho raha hai", paragraphs: ["SellerHisab supplied settlement aur cost data se dekhta hai ki failed order me average kitna loss ho raha hai. Safe failure threshold = successful order ka average contribution ÷ (successful order ka average contribution + failed order ka average loss). Data kam ho to result ko Insufficient Data dikhaya jata hai, guess nahi kiya jata."] },
  { title: "Ads ka kharcha kaise count hota hai", paragraphs: ["Agar SKU-level ad spend milta hai to wahi use hota hai. Sirf total ad spend mile to SellerHisab available sales share ke basis par estimate karta hai aur result ko estimated batata hai. Break-even ROAS = attributable sales ÷ pre-ad contribution. Max ACoS = pre-ad contribution ÷ attributable sales."] },
  { title: "Break-even price: minimum kitne me bechna chahiye", paragraphs: ["Simple idea: product cost + packaging + variable cost + ads + expected Return/RTO loss ko cover karne ke liye selling price kitni honi chahiye. Approximate break-even price = required cost ÷ observed retained settlement rate. Jo assumptions use hoti hain, result ke saath visible rakhi jati hain."] },
  { title: "Order aaj, settlement baad me aaye to?", paragraphs: ["Order, Return/RTO, settlement aur adjustment alag dates ya months me aa sakte hain. SellerHisab multiple periods ko Sub-Order Number se match karta hai. Jab tak final result clear na ho, amount Provisional reh sakta hai."] },
  { title: "Settlement aur bank me amount alag ho to?", paragraphs: ["Optional bank data se SellerHisab settlement total aur bank me actual credit ko compare kar sakta hai. Difference dikhe to woh review signal hai, seedha missing payment ka proof nahi. Kabhi payout batching, refund ya different period ki wajah se bhi difference ho sakta hai."] },
]} note="SellerHisab decision support ke liye analytical estimate deta hai; ye tax, legal ya CA/accounting advice ka replacement nahi hai. Report aur cost data jitna complete hoga, result utna useful hoga." />; }
