import {it,expect,vi,beforeEach} from 'vitest';import {testDatabase} from '../helpers/d1';import {seedConnector} from '../helpers/connector-fixture';import {hmacSha256} from '@/server/crypto';
const state=vi.hoisted(()=>({db:null as D1Database|null,consume:vi.fn(),upsert:vi.fn(),probe:vi.fn()}));
vi.mock('@/server/runtime',()=>({getD1:()=>state.db,runtimeEnv:()=>({SHOPIFY_CLIENT_SECRET:'fixture-signing-secret'})}));
vi.mock('@/server/connectors/store',()=>({consumeOauthStateForCallback:state.consume,upsertConnectedAccount:state.upsert}));vi.mock('@/server/connectors/providers',()=>({woocommerceApiGet:state.probe}));
import {POST as shopify} from '@/app/api/connectors/shopify/webhook/route';import {POST as woo} from '@/app/api/connectors/woocommerce/callback/route';
beforeEach(()=>{const db=testDatabase();seedConnector(db.sqlite);state.db=db.d1;db.sqlite.exec("UPDATE connector_connections SET connector_id='shopify-v1'; UPDATE channel_accounts SET external_account_id='fixture.myshopify.com'");state.consume.mockReset().mockResolvedValueOnce({userId:'u',tenantId:'t',context:{storeUrl:'https://fixture-store.example.com'}}).mockResolvedValue(null);state.upsert.mockReset();state.probe.mockReset().mockResolvedValue([]);});
async function notification(signatureValid=true){const body=JSON.stringify({created_at:'2018-01-01',email:'PRIVATE_CUSTOMER_EMAIL'});const hex=await hmacSha256('fixture-signing-secret',body);return new Request('https://sellerhisab.com/api/connectors/shopify/webhook',{method:'POST',headers:{'x-shopify-hmac-sha256':signatureValid?Buffer.from(hex,'hex').toString('base64'):'invalid','x-shopify-shop-domain':'fixture.myshopify.com','x-shopify-event-id':'event-1','x-shopify-topic':'refunds/create'},body});}
it('verifies raw Shopify HMAC, deduplicates notification and excludes raw seller fields',async()=>{expect((await shopify(await notification(false))).status).toBe(401);expect((await shopify(await notification())).status).toBe(200);expect((await shopify(await notification())).status).toBe(200);const rows=await state.db!.prepare('SELECT * FROM connector_notifications').all();expect(rows.results).toHaveLength(1);expect(JSON.stringify(rows.results)).not.toContain('PRIVATE_CUSTOMER_EMAIL');});
it('returns a retryable response when durable notification persistence is unavailable',async()=>{state.db={prepare(){throw Error('D1 unavailable');}} as unknown as D1Database;expect((await shopify(await notification())).status).toBe(503);});
function wc(permission='read'){return new Request('https://sellerhisab.com/api/connectors/woocommerce/callback',{method:'POST',body:JSON.stringify({user_id:'fixture-one-use-state-123456',consumer_key:'ck_'+'a'.repeat(40),consumer_secret:'cs_'+'b'.repeat(40),key_permissions:permission})});}
it('accepts only read-only Woo authorization and consumes callback capability once',async()=>{expect((await woo(wc('read_write'))).status).toBe(400);expect(state.consume).not.toHaveBeenCalled();expect((await woo(wc())).status).toBe(201);expect((await woo(wc())).status).toBe(400);expect(state.upsert).toHaveBeenCalledTimes(1);expect(state.upsert.mock.calls[0][0]).toMatchObject({tenantId:'t',userId:'u',grantedScopes:['read'],credential:{storeUrl:'https://fixture-store.example.com',scope:'read'}});});
it('does not save credentials when the SSRF-protected provider probe fails',async()=>{state.probe.mockRejectedValue(Error('Private destination'));expect((await woo(wc())).status).toBe(400);expect(state.upsert).not.toHaveBeenCalled();});
