import {it,expect,vi,beforeEach} from 'vitest';
import {initialCheckpoint} from '@/core/connectors/coverage';
import type {OwnedConnection,StoredConnectorCredential} from '@/server/connectors/store';
const api=vi.hoisted(()=>({amazon:vi.fn(),shopify:vi.fn(),flipkart:vi.fn()}));
vi.mock('@/server/connectors/providers',()=>({amazonSpApiGet:api.amazon,shopifyGraphql:api.shopify,flipkartApi:api.flipkart,providerConstants:{AMAZON_INDIA_MARKETPLACE_ID:'IN'}}));
import {fetchConnectorPage} from '@/server/connectors/pages';
const connection=(connectorId:string)=>({id:'c',connectorId,channelAccountId:'ca'}) as OwnedConnection;
const credential={scope:'read_shopify_payments'} as StoredConnectorCredential;
beforeEach(()=>{api.amazon.mockReset();api.shopify.mockReset();api.flipkart.mockReset();});
it.each([0,1,2])('Amazon stage %i exhausts 40 tokens with serializable resume',async(stage)=>{let c=initialCheckpoint(30);c.stage=stage;api.amazon.mockImplementation(async()=>({payload:{orders:[],transactions:[],FinancialEventGroupList:[],NextToken:api.amazon.mock.calls.length<40?'token-'+api.amazon.mock.calls.length:''}}));for(let n=0;n<40;n++){const result=await fetchConnectorPage(credential,connection('amazon-in-v1'),c);c.cursor=result.next;c=JSON.parse(JSON.stringify(c));}expect(c.cursor).toBe('');expect(api.amazon).toHaveBeenCalledTimes(40);});
it('Flipkart follows 40 pages and rejects foreign pagination destinations',async()=>{const c=initialCheckpoint(30);api.flipkart.mockImplementation(async()=>({shipments:[],nextPageUrl:api.flipkart.mock.calls.length<40?'/sellers/v3/shipments/page/'+api.flipkart.mock.calls.length:''}));for(let n=0;n<40;n++)c.cursor=(await fetchConnectorPage(credential,connection('flipkart-v1'),c)).next;expect(c.cursor).toBe('');expect(c.financeComplete).toBe(false);c.cursor='https://attacker.invalid/';await expect(fetchConnectorPage(credential,connection('flipkart-v1'),c)).rejects.toThrow('unsafe');});
it.each([0,1,2])('Shopify stage %i follows all cursors and preserves cost delay',async(stage)=>{const c=initialCheckpoint(30);c.stage=stage;const field=['orders','balanceTransactions','payouts'][stage];api.shopify.mockImplementation(async()=>{const page={nodes:[],pageInfo:{hasNextPage:api.shopify.mock.calls.length<35,endCursor:'cursor-'+api.shopify.mock.calls.length}};return {data:stage?{shopifyPaymentsAccount:{[field]:page}}:{orders:page},nextReadAt:'2026-09-09T00:00:00Z'};});for(let i=0;i<35;i++)c.cursor=(await fetchConnectorPage(credential,connection('shopify-v1'),c)).next;expect(c.cursor).toBe('');expect(c.notBefore).toBe('2026-09-09T00:00:00Z');});
it('nested Shopify line pages finish before advancing the outer order cursor',async()=>{const c=initialCheckpoint(30);const order={id:'gid://shopify/Order/1',name:'#1',createdAt:'2026-01-01',lineItems:{nodes:[],pageInfo:{hasNextPage:true,endCursor:'line-1'}}};api.shopify.mockResolvedValueOnce({data:{orders:{nodes:[order],pageInfo:{hasNextPage:true,endCursor:'order-2'}}}}).mockResolvedValueOnce({data:{order:{...order,lineItems:{nodes:[],pageInfo:{hasNextPage:false,endCursor:null}}}}});c.cursor=(await fetchConnectorPage(credential,connection('shopify-v1'),c)).next;expect(c.cursor).toMatch(/^lines:/);c.cursor=(await fetchConnectorPage(credential,connection('shopify-v1'),c)).next;expect(c.cursor).toBe('order-2');});
it('malformed and repeated cursors cannot report complete coverage',async()=>{const c=initialCheckpoint(30);api.shopify.mockResolvedValue({data:{orders:{nodes:[]}}});await expect(fetchConnectorPage(credential,connection('shopify-v1'),c)).rejects.toThrow('pagination_metadata_missing');c.cursor='same';api.amazon.mockResolvedValue({payload:{orders:[],NextToken:'same'}});await expect(fetchConnectorPage(credential,connection('amazon-in-v1'),c)).rejects.toThrow('repeated');});

it('Shopify freshness queries updates so changes to older orders are included',async()=>{const c=initialCheckpoint(7);c.orderDateField='updated_at';api.shopify.mockResolvedValue({data:{orders:{nodes:[],pageInfo:{hasNextPage:false}}}});await fetchConnectorPage(credential,connection('shopify-v1'),c);expect(api.shopify.mock.calls[0][2].query).toContain('updated_at:>=');});
